# App-specific netlify.toml
[build]
  base = "apps/dhg-a"
  command = "VITE_ENV=$CONTEXT pnpm build"
  publish = "dist"

# App-specific environment overrides
[context.production.environment]
  VITE_APP_NAME = "DHG Hub"
  VITE_ENV = "production"
  VITE_FEATURE_FLAGS = "release"

[context.development.environment]
  VITE_APP_NAME = "DHG Hub (Dev)"
  VITE_ENV = "development"
  VITE_FEATURE_FLAGS = "debug,beta"

[context.deploy-preview.environment]
  VITE_APP_NAME = "DHG Hub (Preview)"
  VITE_ENV = "preview"
  VITE_FEATURE_FLAGS = "debug,beta,experimental"

[context.branch-deploy.environment]
  VITE_APP_NAME = "DHG Hub (Branch)"
  VITE_ENV = "preview"
  VITE_FEATURE_FLAGS = "debug,beta,experimental"

[context.feature-enhanced-env-display.environment]
  VITE_APP_NAME = "DHG Hub (Feature Branch)"
  VITE_ENV = "preview"
  VITE_FEATURE_FLAGS = "debug,beta,experimental" 