#!/bin/bash
# Auto-generated copy commands

cp "/Users/raybunnage/Google Drive/My Drive/500_AI_Process/501_Input_File_Types/503_Input_MP4s/2024_09_15_Wilkinson.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/INGESTED_2024_09_15_Wilkinson.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/Dynamic Healing Discussion Group/2025-02-19-Stockdale - Exceptional Cancer Survivors/Presentation  Summary/Stockdale_Seigel_2.19.25.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Stockdale_Seigel_2.19.25.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/900_Legacy All Domains/599_AI-Process Legacy/596_AI-Inputs/556_Training Transcripts/2024-02-21-Where do we go from here Carter.Clawson,HanscomDHDG.2.21.24.open Discussion.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/DHDG.2.21.24.open Discussion.mp4"
# File not found: INGESTED_2024_10_02_Clawson_sapiocortex_anger.mp4
cp "/Users/raybunnage/Google Drive/My Drive/Dynamic Healing Discussion Group/2024-01-10-Bernie Seigel - a conversation/Bernie Seigel.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Bernie Seigel.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/900_Legacy All Domains/599_AI-Process Legacy/596_AI-Inputs/556_Training Transcripts/2024-01-24-Naviaux DR -Update chronic fatigue Naviaux.DR.1.24.24.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Naviaux.DR.1.24.24.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/500_AI_Process/501_Input_File_Types/503_Input_MP4s/2024_10_16_Panda_circadian_medicine.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/INGESTED_2024_10_16_Panda_circadian_medicine.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/000_DHG Repository/001_DHG Getting Started/002_DHG Instructions/Lionya Work/A1-Transcription_Tool/Lionya's work on the app/A1-Transcription_Tool/file_types/mp4s/2024_11_08_Steering.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/INGESTED_2024_11_08_Steering.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/Dynamic Healing Discussion Group/2023-11-15-Staats.Clawson.VNS.Steroids/Staats.Clawson.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Staats.Clawson.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/400_AI-Publish/420_Curated Presentations/DR Sapiocortex Anger/Clawson.sapiocortex.anger.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Clawson.sapiocortex.anger 2.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/000_DHG Repository/001_DHG Getting Started/002_DHG Instructions/Lionya Work/A1-Transcription_Tool/Lionya's work on the app/A1-Transcription_Tool/file_types/mp4s/Clawson_Anger_2024_09_04_transcript.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Clawson_Anger_2024_09_04_transcript 2.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/000_DHG Repository/001_DHG Getting Started/002_DHG Instructions/Lionya Work/A1-Transcription_Tool/Lionya's work on the app/A1-Transcription_Tool/file_types/mp4s/Clawson_sapiocortex_anger_2024_10_02.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Clawson_sapiocortex_anger_2024_10_02 2.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/Dynamic Healing Discussion Group/2023-05-03-Sullivan Ballantyne - Opioids updated/Sullivan.Ballantyne.5.3.23.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Sullivan.Ballantyne.5.3.23.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/000_DHG Repository/001_DHG Getting Started/002_DHG Instructions/Lionya Work/A1-Transcription_Tool/Lionya's work on the app/A1-Transcription_Tool/file_types/mp4s/Cook_Clawson_2024_05_22.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Cook_Clawson_2024_05_22 2.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/200_Research Experts/210_Research Experts/212_Carter Scaffold/2128_Carter Videos Presentations/Copy of Carter.8.26.20.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Copy of Carter.8.26.20.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/Dynamic Healing Discussion Group/2023-03-01-Rownena Field - Ketogenic Diet - Pain/Rowena Field.3.1.23.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Rowena Field.3.1.23.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/500_AI_Process/501_Input_File_Types/503_Input_MP4s/Copy of Clawson_sapiocortex_anger.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Copy of Clawson_sapiocortex_anger.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/Dynamic Healing Discussion Group/2021-10-06-Kovacic.Porges.ANS and the gut/Kovacic.Porges.`106.21.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Kovacic.Porges.`106.21.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/Dynamic Healing Discussion Group/2020-12-16-Eagle-Armster-A.W.E somatic work/Eagle.Armster.12.16.20.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Eagle.Armster.12.16.20.mp4"
cp "/Users/raybunnage/Google Drive/My Drive/Dynamic Healing Discussion Group/2020-06-10-Anger-vulnerability/Ring of Fire.7.7.20.mp4" "/Users/raybunnage/Documents/github/dhg-mono/file_types/mp4/Ring of Fire.7.7.20.mp4"