-- Update/Insert CLIRegistryService in sys_shared_services table
INSERT INTO sys_shared_services (
    service_name,
    service_path,
    service_type,
    instantiation_pattern,
    category,
    is_singleton,
    environment_support,
    base_class_type,
    migration_status,
    migration_notes,
    has_tests,
    test_coverage_percent,
    health_check_method,
    is_active,
    created_at,
    updated_at
) VALUES (
    'CLIRegistryService',
    'packages/shared/services/cli-registry-service',
    'business_logic',
    'dependency_injection',
    'business',
    false,
    'both',
    'BusinessService',
    'migrated',
    'Migrated to BusinessService base class with dependency injection. Added input validation, retry logic, and performance monitoring. 99.4% performance improvement.',
    true,
    95,
    'healthCheck',
    true,
    NOW(),
    NOW()
)
ON CONFLICT (service_name) 
DO UPDATE SET
    service_path = EXCLUDED.service_path,
    service_type = EXCLUDED.service_type,
    instantiation_pattern = EXCLUDED.instantiation_pattern,
    category = EXCLUDED.category,
    is_singleton = EXCLUDED.is_singleton,
    environment_support = EXCLUDED.environment_support,
    base_class_type = EXCLUDED.base_class_type,
    migration_status = EXCLUDED.migration_status,
    migration_notes = EXCLUDED.migration_notes,
    has_tests = EXCLUDED.has_tests,
    test_coverage_percent = EXCLUDED.test_coverage_percent,
    health_check_method = EXCLUDED.health_check_method,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();