-- Insert all remaining google sync commands discovered from file analysis
-- These are mostly test/debug/utility files that should be archived

INSERT INTO command_refactor_tracking (command_name, description, command_type, current_status, notes) VALUES
-- Test and debug commands
('add-find-duplicates-function', 'Add find duplicates function to database', 'utility', 'deprecated', 'Archive - database utility, not CLI command'),
('analyze-audio-gaps', 'Analyze gaps in audio file coverage', 'analysis', 'deprecated', 'Archive - one-time analysis script'),
('analyze-command-usage', 'Analyze command usage statistics', 'analysis', 'deprecated', 'Archive - analysis utility'),
('analyze-document-types-path-depth', 'Analyze document types by path depth', 'analysis', 'deprecated', 'Archive - analysis utility'),
('analyze-expert-documents', 'Analyze expert documents', 'analysis', 'deprecated', 'Archive - analysis utility'),
('analyze-folders-query', 'Analyze folders query performance', 'analysis', 'deprecated', 'Archive - analysis utility'),

-- Check commands (mostly debug/test)
('check-concepts-of-document', 'Check concepts for specific document', 'debug', 'deprecated', 'Archive - debug utility'),
('check-concepts', 'Check document concepts', 'debug', 'deprecated', 'Archive - debug utility'),
('check-deleted-files', 'Check for deleted files', 'debug', 'deprecated', 'Archive - debug utility'),
('check-document-ids', 'Validate document IDs', 'debug', 'deprecated', 'Archive - debug utility'),
('check-document-status', 'Check document processing status', 'debug', 'deprecated', 'Archive - debug utility'),
('check-document-types', 'Check document type assignments', 'debug', 'deprecated', 'Archive - debug utility'),
('check-duplicate-prevention', 'Check duplicate prevention logic', 'debug', 'deprecated', 'Archive - debug utility'),
('check-expert-docs', 'Check expert documents integrity', 'debug', 'deprecated', 'Archive - debug utility'),
('check-m4a-mp4-relationship', 'Check m4a to mp4 relationships', 'debug', 'deprecated', 'Archive - debug utility'),
('check-mp4-status', 'Check MP4 file processing status', 'debug', 'deprecated', 'Archive - debug utility'),
('check-path-depths', 'Check path depth calculations', 'debug', 'deprecated', 'Archive - debug utility'),
('check-pptx-files', 'Check PowerPoint file status', 'debug', 'deprecated', 'Archive - debug utility'),
('check-recent-updates', 'Check recently updated files', 'debug', 'deprecated', 'Archive - debug utility'),
('check-reprocessing-status', 'Check files marked for reprocessing', 'debug', 'deprecated', 'Archive - debug utility'),
('check-table-schema', 'Check database table schema', 'debug', 'deprecated', 'Archive - debug utility'),
('check-updated-fields', 'Check updated field values', 'debug', 'deprecated', 'Archive - debug utility'),

-- Classification utilities (old implementations)
('classify-missing-docs-with-service', 'Classify missing documents', 'classification', 'deprecated', 'Archive - old implementation'),
('classify-pdfs-with-service', 'Classify PDFs using service', 'classification', 'deprecated', 'Archive - old implementation'),
('classify-unprocessed-with-content', 'Classify unprocessed files', 'classification', 'deprecated', 'Archive - old implementation'),
('direct-classify-pdfs', 'Direct PDF classification', 'classification', 'deprecated', 'Archive - old implementation'),
('force-classify-docs', 'Force document classification', 'classification', 'deprecated', 'Archive - old implementation'),
('force-reclassify', 'Force reclassification of documents', 'classification', 'deprecated', 'Archive - old implementation'),
('reclassify-docs-helper', 'Helper for document reclassification', 'classification', 'deprecated', 'Archive - old implementation'),
('reclassify-docs-with-service', 'Reclassify using service', 'classification', 'deprecated', 'Archive - old implementation'),
('reclassify_docs_helper', 'Legacy reclassify helper', 'classification', 'deprecated', 'Archive - old implementation'),
('reprocess-docx-files', 'Reprocess DOCX files', 'classification', 'deprecated', 'Archive - old implementation'),
('run-classify-pdfs', 'Run PDF classification', 'classification', 'deprecated', 'Archive - old implementation'),
('validate-pdf-classification', 'Validate PDF classifications', 'classification', 'deprecated', 'Archive - old implementation'),

-- Maintenance/fix utilities
('clear-reprocessing', 'Clear reprocessing flags', 'maintenance', 'deprecated', 'Archive - use mark command instead'),
('copy-data-to-sources-google', 'Copy data migration utility', 'maintenance', 'deprecated', 'Archive - one-time migration'),
('create-google-sources-experts', 'Create junction table', 'maintenance', 'deprecated', 'Archive - one-time setup'),
('create-sources-google', 'Create sources table', 'maintenance', 'deprecated', 'Archive - one-time setup'),
('delete-file-from-db', 'Delete file from database', 'maintenance', 'deprecated', 'Archive - dangerous utility'),
('delete-orphaned-records', 'Delete orphaned records', 'maintenance', 'deprecated', 'Archive - use fix command instead'),
('expert-documents-duplicates', 'Find duplicate expert documents', 'maintenance', 'deprecated', 'Archive - use check command instead'),
('expert-documents-purge', 'Purge expert documents', 'maintenance', 'deprecated', 'Archive - dangerous utility'),
('finalize-rename', 'Finalize table rename', 'maintenance', 'deprecated', 'Archive - one-time migration'),
('fix-bad-folders', 'Fix bad folder types', 'maintenance', 'deprecated', 'Archive - use fix command instead'),
('fix-classify-pdfs', 'Fix PDF classification', 'maintenance', 'deprecated', 'Archive - old implementation'),
('fix-mp4-processing-status', 'Fix MP4 processing status', 'maintenance', 'deprecated', 'Archive - old implementation'),
('fix-root-path-depth', 'Fix root path depths', 'maintenance', 'deprecated', 'Archive - one-time fix'),
('fix-specific-document', 'Fix specific document', 'maintenance', 'deprecated', 'Archive - debug utility'),
('identify-orphaned-records', 'Identify orphaned records', 'maintenance', 'deprecated', 'Archive - use check command instead'),
('insert-missing-sources', 'Insert missing source records', 'maintenance', 'deprecated', 'Archive - one-time fix'),
('insert-specific-file', 'Insert specific file', 'maintenance', 'deprecated', 'Archive - debug utility'),
('migrate-sources-google', 'Migrate sources table', 'maintenance', 'deprecated', 'Archive - one-time migration'),
('purge-orphaned-with-presentations', 'Purge orphaned presentations', 'maintenance', 'deprecated', 'Archive - dangerous utility'),
('renamed-file', 'Handle renamed file', 'maintenance', 'deprecated', 'Archive - old implementation'),
('reset-and-mark-for-processing', 'Reset and mark files', 'maintenance', 'deprecated', 'Archive - use mark command instead'),
('reset-deleted-files', 'Reset deleted file flags', 'maintenance', 'deprecated', 'Archive - old implementation'),
('reset-document-type', 'Reset document type', 'maintenance', 'deprecated', 'Archive - old implementation'),
('reset-sources-processing-status', 'Reset processing status', 'maintenance', 'deprecated', 'Archive - use mark command instead'),
('run-fix-many-documents', 'Fix many documents', 'maintenance', 'deprecated', 'Archive - old implementation'),
('update-document-type-id', 'Update document type ID', 'maintenance', 'deprecated', 'Archive - old implementation'),
('update-file-signatures', 'Update file signatures', 'maintenance', 'deprecated', 'Archive - old implementation'),
('update-main-video-ids', 'Update main video IDs', 'maintenance', 'deprecated', 'Archive - old implementation'),
('update-paths-and-roots', 'Update paths and roots', 'maintenance', 'deprecated', 'Archive - one-time fix'),
('update-pipeline-status', 'Update pipeline status', 'maintenance', 'deprecated', 'Archive - use mark command instead'),
('update-processed-records', 'Update processed records', 'maintenance', 'deprecated', 'Archive - old implementation'),
('update-schema-from-json', 'Update schema from JSON', 'maintenance', 'deprecated', 'Archive - one-time migration'),
('update-sources-from-json', 'Update sources from JSON', 'maintenance', 'deprecated', 'Archive - one-time migration'),

-- Media utilities
('count-mp4-files', 'Count MP4 files', 'media', 'deprecated', 'Archive - use list command instead'),
('generate-audio-batch', 'Generate audio batch', 'media', 'deprecated', 'Archive - use media command instead'),
('generate-main-video-files-report', 'Generate video files report', 'media', 'deprecated', 'Archive - use report command instead'),
('list-main-video-folders-tree', 'List video folder tree', 'media', 'deprecated', 'Archive - use list command instead'),
('list-main-video-folders', 'List video folders', 'media', 'deprecated', 'Archive - use list command instead'),
('upload-audio-files', 'Upload audio files', 'media', 'deprecated', 'Archive - not implemented'),

-- Listing utilities
('list-unclassified-files', 'List unclassified files', 'listing', 'deprecated', 'Archive - use list --status unclassified'),
('list-unsupported-document-types', 'List unsupported types', 'listing', 'deprecated', 'Archive - use report command instead'),
('pipeline-status-summary', 'Pipeline status summary', 'listing', 'deprecated', 'Archive - use report command instead'),
('show-tables', 'Show database tables', 'listing', 'deprecated', 'Archive - debug utility'),

-- Other utilities
('display-active-filter', 'Display active filter', 'filter', 'deprecated', 'Archive - filter system deprecated'),
('find-documents-with-content', 'Find documents with content', 'search', 'deprecated', 'Archive - use search command instead'),
('index', 'Index file for commands', 'utility', 'deprecated', 'Archive - not a command'),
('needs-reprocessing', 'Check files needing reprocessing', 'utility', 'deprecated', 'Archive - use list command instead'),
('process-unprocessed', 'Process unprocessed files', 'utility', 'deprecated', 'Archive - old implementation'),
('simple-document-check', 'Simple document check', 'utility', 'deprecated', 'Archive - debug utility'),
('source-info', 'Get source information', 'utility', 'deprecated', 'Archive - debug utility'),
('sync-and-update-metadata', 'Sync and update metadata', 'utility', 'deprecated', 'Archive - use sync-all instead'),
('test-active-filter', 'Test active filter', 'test', 'deprecated', 'Archive - test file'),
('test-direct-sql', 'Test direct SQL', 'test', 'deprecated', 'Archive - test file'),
('test-prompt-service', 'Test prompt service', 'test', 'deprecated', 'Archive - test file'),
('test-query', 'Test query', 'test', 'deprecated', 'Archive - test file'),
('test-skip-reprocessing', 'Test skip reprocessing', 'test', 'deprecated', 'Archive - test file'),
('test-source-extensions', 'Test source extensions', 'test', 'deprecated', 'Archive - test file'),
('verify-file-in-db', 'Verify file in database', 'utility', 'deprecated', 'Archive - debug utility')
ON CONFLICT (command_name) DO UPDATE
SET current_status = EXCLUDED.current_status,
    notes = EXCLUDED.notes;