# App-specific netlify.toml
[build]
  base = "apps/dhg-improve-experts"
  command = "pnpm build"
  publish = "dist"

# App-specific environment overrides
[context.production]
  [context.production.environment]
    VITE_APP_NAME = "DHG Improve Experts"
    VITE_SUPABASE_URL = "https://jdksnfkupzywjdfefkyj.supabase.co"

[context.development]
  [context.development.environment]
    VITE_APP_NAME = "DHG Improve Experts (Dev)"
    VITE_SUPABASE_URL = "https://jdksnfkupzywjdfefkyj.supabase.co"

[context.deploy-preview]
  [context.deploy-preview.environment]
    VITE_APP_NAME = "DHG Improve Experts (Preview)"
    VITE_SUPABASE_URL = "https://jdksnfkupzywjdfefkyj.supabase.co"

[build.environment]
  NODE_VERSION = "20.9.0"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 