# Media Processing Configuration
# This file controls the behavior of the unified media processing pipeline

sources:
  google_drive:
    # Root path to your Google Drive (via Google Drive Desktop)
    root: "/Users/raybunnage/Library/CloudStorage/GoogleDrive-bunnage.ray@gmail.com/My Drive"
    # Folders to search for media files
    folders:
      - "200_Research Experts"
      - "Dynamic Healing Discussion Group"
      - "000_DHG"
      - "100_Healing Journeys"

processing:
  # Directory for temporary file storage
  temp_dir: "./file_types"
  # Maximum parallel processing jobs
  max_parallel: 3
  # Default Whisper model for transcription
  default_model: "whisper-large-v3"
  # Default GPU accelerator
  default_accelerator: "A10G"
  # File size limit for processing (in MB)
  max_file_size: 5000

storage:
  # Automatically cleanup old files
  auto_cleanup: true
  # Maximum cache size
  max_cache_size: "50GB"
  # Days to retain processed files
  retention_days: 7
  # Cleanup processed files immediately after upload
  cleanup_after_upload: false

transcription:
  # Models available for transcription
  models:
    tiny: "openai/whisper-tiny"
    base: "openai/whisper-base"
    small: "openai/whisper-small"
    medium: "openai/whisper-medium"
    large: "openai/whisper-large-v3"
  # Accelerators available
  accelerators:
    - "T4"
    - "A10G"
    - "A100"
  # Default language
  language: "en"
  # Temperature for transcription
  temperature: 0.0

upload:
  # Upload M4A files back to Google Drive
  upload_m4a: true
  # Create subfolder for M4A files
  m4a_subfolder: "audio_files"
  # Upload transcripts
  upload_transcripts: false
  # Upload summaries
  upload_summaries: false

logging:
  # Log level: DEBUG, INFO, WARN, ERROR
  level: "INFO"
  # Log to file
  log_to_file: true
  # Log file path
  log_file: "./logs/media-processing.log"
  # Max log file size before rotation
  max_log_size: "10MB"
  # Number of log files to keep
  max_log_files: 5