// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a single instance
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

export const getSupabaseClient = () => {
  if (!supabaseInstance) {
    supabaseInstance = createClient<Database>(
      import.meta.env.VITE_SUPABASE_URL,
      import.meta.env.VITE_SUPABASE_ANON_KEY,
      {
        auth: {
          storageKey: 'dhg-supabase-auth',
          persistSession: true
        }
      }
    );
  }
  return supabaseInstance;
};

const SUPABASE_URL = "https://jdksnfkupzywjdfefkyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "***REMOVED***";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);