// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const SUPABASE_URL = "https://jdksnfkupzywjdfefkyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "***REMOVED***";

// Create a single supabase instance with specific storage key
// Note: autoRefreshToken is true by default, but explicitly stated for clarity
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storageKey: 'dhg-supabase-auth',
    persistSession: true,
    autoRefreshToken: true
  }
});

// For backwards compatibility
export const getSupabaseClient = () => supabase;